### ISSUE TITLE
Build error: undeclared identifier 'NPY_ARRAY_UPDATEIFCOPY'

### ISSUE THREAD

**Issue by tgoldina** [dstndstn/tractor#100]
When using the recent version of numpy (e.g. 1.23.5), `pip install git+https://github.com/dstndstn/tractor.git@main` fails with an error:
```
use of undeclared identifier 'NPY_ARRAY_UPDATEIFCOPY'
```
Replacing all occurrences of `NPY_ARRAY_UPDATEIFCOPY` with `NPY_ARRAY_WRITEBACKIFCOPY` cures the issue.

**Comment by dstndstn** [comment]
What version of the Astrometry.net code are you testing on?  I thought this was already fixed in main (in June 2022).

**Comment by dstndstn** [comment]
Should be fixed in 676f8fc75b8dd385559f29968821fa7675acb251.
