### ISSUE TITLE
PixelizedPsfEx keyword for XY [POLNAME1,POLNAME2]

### ISSUE THREAD

**Issue by marcogullieuszik** [dstndstn/tractor#109]
I am just starting using tractor.

PixelizedPsfEx requires that PSFEX (and sextractor) use (X_IMAGE, Y_IMAGE) to define the source positions in the code line
"assert(hdr['POLNAME1'].strip() == 'X_IMAGE')"

It would be extremely useful to add the option of using other sextractor positional parameters.
For example, I usually use XWIN_IMAGE and YWIN_IMAGE as they provide more accurate centroid positions.

As a workaround I am now changing the "POLNAME1","POLNAME2" keywords in the PSFEX file

**Comment by dstndstn** [comment]
Good idea!  If you want to send a Pull Request with that improvement, that would be great!

**Comment by marcogullieuszik** [comment]
s
