### ISSUE TITLE
SFD maps

### ISSUE THREAD

**Issue by davidwhogg** [dstndstn/tractor#34]
We should probably divide them out at modeling time, if we can.

**Comment by davidwhogg** [comment]
oh wait I mean "multiply them in" to our model.

**Comment by dstndstn** [comment]
This would be particularly cool if one had a more elaborate galaxy model,
like a particular spectrum at a particular redshift.  Then you could
compute the reddening for that particular object, not a generic source.

​

**Comment by dstndstn** [comment]
There is no explicit action item in this issue, so am closing it.  Feel free to redirect.
