### ISSUE TITLE
Error RE: Non-ASCII character '\xd3 in mix.py? 

### ISSUE THREAD

**Issue by djbard** [dstndstn/tractor#61]
Hello,
 I'm using the master of tractor, and astrometry 0.50. It appears to compile and install fine, but running the example gives me the following error:

----------------------------
[ki-ls10] $ python examples/tractor-sdss-synth.py

Demo mode: grabbing Run/Camcol/Field/Band 1752/3/164/r
Using SDSS DR9 data

Checking for file psField-001752-3-0164.fit
Checking for file fpM-001752-r3-0164.fit
Checking for file frame-r-001752-3-0164.fits.bz2
command: TMPFILE=$(mktemp /tmp/tmpULO2Lm.tmp.XXXXXX) && bunzip2 -cd frame-r-001752-3-0164.fits.bz2 > $TMPFILE && mv $TMPFILE /tmp/tmpULO2Lm

Frame filename /tmp/tmpULO2Lm
Looking for file photoObj-001752-3-0164.fits
Created 11 deV, 21 exp, 21 composite (total 53) galaxies and 19 stars
Traceback (most recent call last):
  File "examples/tractor-sdss-synth.py", line 477, in <module>
    cProfile.run('main()', 'prof-%s.dat' % (datetime.now().isoformat()))
  File "/afs/slac/g/lsst/software/redhat6-x86_64-64bit-gcc44/DMstack/Winter2013-v6_2/Linux64/external/python/2.7.3+1/lib/python2.7/cProfile.py", line 29, in run
    prof = prof.run(statement)
  File "/afs/slac/g/lsst/software/redhat6-x86_64-64bit-gcc44/DMstack/Winter2013-v6_2/Linux64/external/python/2.7.3+1/lib/python2.7/cProfile.py", line 135, in run
    return self.runctx(cmd, dict, dict)
  File "/afs/slac/g/lsst/software/redhat6-x86_64-64bit-gcc44/DMstack/Winter2013-v6_2/Linux64/external/python/2.7.3+1/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "examples/tractor-sdss-synth.py", line 341, in main
    save('initial-%s-' % (band) + prefix, tractor, imgi=j, **sa)
  File "examples/tractor-sdss-synth.py", line 23, in save
    mod = tractor.getModelImage(imgi)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/engine.py", line 2453, in getModelImage
    patch = self.getModelPatch(img, src, minsb=minsb)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/engine.py", line 2427, in getModelPatch
    mod = self.getModelPatchNoCache(img, src, minsb=minsb, **kwargs)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/engine.py", line 2401, in getModelPatchNoCache
    mod = src.getModelPatch(img, modelMask=mask, **kwargs)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/basics.py", line 882, in getModelPatch
    upatch = self.getUnitFluxModelPatch(img, minval=minval, modelMask=modelMask)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/basics.py", line 939, in getUnitFluxModelPatch
    minradius=self.minRadius, modelMask=modelMask)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/basics.py", line 1321, in getPointSourcePatch
    return self.mog.evaluate_grid(x0, x1, y0, y1, px, py)
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/mixture_profiles.py", line 233, in evaluate_grid_dstn
    from mix import c_gauss_2d_grid
  File "/u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/mix.py", line 1
SyntaxError: Non-ASCII character '\xd3' in file /u/br/djbard/LSST/great3/tractor-master/tractor/install/lib/python2.7/site-packages/tractor/mix.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

--------------------------------
mix.py appears to be a binary file. Is this likely to be a problem with my setup somehow?

 thanks,
  Debbie

**Comment by dstndstn** [comment]
Uhh, that's weird!

mix.py is generated by swig from mix.i -- could you try

rm tractor/mix.py tractor/_mix.so
make

and send the logs?

thx!

**Comment by djbard** [comment]
It is odd! Do the examples run fine for you? 
The resulting make log is as follows:

=======================================================================
[djbard@ki-rh54 tractor]$ rm tractor/mix.py tractor/_mix.so 
[djbard@ki-rh54 tractor]$ make 
make -C tractor mix
make -C tractor emfit
make[1]: Entering directory `/nfs/slac/g/ki/ki06/lsst/djbard/LSST/great3/tractor-master/tractor/tractor'
python setup-mix.py build --force --build-base build --build-platlib build/lib
python setup-mix.py build --force --build-base build --build-platlib build/lib
make[1]: Entering directory `/nfs/slac/g/ki/ki06/lsst/djbard/LSST/great3/tractor-master/tractor/tractor'
make[1]: Nothing to be done for `emfit'.
make[1]: Leaving directory `/nfs/slac/g/ki/ki06/lsst/djbard/LSST/great3/tractor-master/tractor/tractor'
running build
running build_ext
running build
running build_ext
building '_mix' extension
swigging mix.i to mix_wrap.c
swig -python -o mix_wrap.c mix.i
building '_mix' extension
swigging mix.i to mix_wrap.c
swig -python -o mix_wrap.c mix.i
C compiler: gcc -pthread -fno-strict-aliasing -I/opt/lsst/rhel-6-x86_64/Linux64/external/astrometry_net/0.30/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include -I/afs/slac/g/lsst/software/redhat6-x86_64-64bit-gcc44/DMstack/Winter2013-v6_2/Linux64/external/python/2.7.3+1/include/python2.7 -c'
gcc: mix_wrap.c
C compiler: gcc -pthread -fno-strict-aliasing -I/opt/lsst/rhel-6-x86_64/Linux64/external/astrometry_net/0.30/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include -I/afs/slac/g/lsst/software/redhat6-x86_64-64bit-gcc44/DMstack/Winter2013-v6_2/Linux64/external/python/2.7.3+1/include/python2.7 -c'
gcc: mix_wrap.c
In file included from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/ndarraytypes.h:1761,
                 from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/arrayobject.h:4,
                 from mix_wrap.c:2696:
/u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
In file included from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/ndarraytypes.h:1761,
                 from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/arrayobject.h:4,
                 from mix_wrap.c:2696:
/u/ki/dstn/software/numpy-1.8.1/lib/python/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
In file included from mix_wrap.c:3755:
approx3.c: In function 'c_gauss_2d_approx3':
approx3.c:38: warning: unused variable 'nexp0'
In file included from mix_wrap.c:3770:
gauss_masked.c: In function 'c_gauss_2d_masked':
gauss_masked.c:21: warning: unused variable 'n_fnan0'
gauss_masked.c:20: warning: unused variable 'n_finf0'
gauss_masked.c:18: warning: unused variable 'nexpf0'
In file included from mix_wrap.c:3755:
approx3.c: In function 'c_gauss_2d_approx3':
approx3.c:38: warning: unused variable 'nexp0'
In file included from mix_wrap.c:3770:
gauss_masked.c: In function 'c_gauss_2d_masked':
gauss_masked.c:21: warning: unused variable 'n_fnan0'
gauss_masked.c:20: warning: unused variable 'n_finf0'
gauss_masked.c:18: warning: unused variable 'nexpf0'
gcc -pthread -shared -L/opt/lsst/rhel-6-x86_64/Linux64/external/astrometry_net/0.30/lib build/temp.linux-x86_64-2.7/mix_wrap.o -L/opt/lsst/rhel-6-x86_64/Linux64/external/python/2.7.3+1/lib -lpython2.7 -o build/lib/_mix.so
gcc -pthread -shared -L/opt/lsst/rhel-6-x86_64/Linux64/external/astrometry_net/0.30/lib build/temp.linux-x86_64-2.7/mix_wrap.o -L/opt/lsst/rhel-6-x86_64/Linux64/external/python/2.7.3+1/lib -lpython2.7 -o build/lib/_mix.so
cp build/lib/_mix.so _mix.so
cp build/lib/_mix.so mix.py
make[1]: Leaving directory `/nfs/slac/g/ki/ki06/lsst/djbard/LSST/great3/tractor-master/tractor/tractor'

=======================================================================
