### ISSUE TITLE
projects/desi/runbrick.py

### ISSUE THREAD

**Issue by rainwoodman** [dstndstn/tractor#64]
dimshow is not in plotutils from the standard astrometry.net 0.5pre distribution.

Shall I update astrometry.net to a different version? Which one shall it be?

"""
Traceback (most recent call last):
  File "runbrick.py", line 25, in <module>
    from astrometry.util.plotutils import PlotSequence, dimshow
ImportError: cannot import name dimshow
"""

**Comment by dstndstn** [comment]
Sorry, I think any astrometry.net release >= 0.51 should have this.  Best to grab the latest (0.56);
https://github.com/dstndstn/astrometry.net/releases/tag/0.56
