### ISSUE TITLE
Bias in small stamp size

### ISSUE THREAD

**Issue by DriftingPig** [dstndstn/tractor#86]
Hi Dustin,
I'm just curious about this. If I define a Gaussian distribution, with mean,sigma. Then I draw random points from this Gaussian distribution and add them in a binned histogram. If the binning is large, then the sigma that I can get from this binned histogram will converge to a larger sigma value. And because of this, the half radius of galaxies will be larger than they actually are. Does tractor correct for this effect?

**Comment by dstndstn** [comment]
I'm not really sure what you're talking about.  We use mixtures of Gaussians as approximations of the deV and exp radial light profiles.  These are evaluated (after convolution by the PSF) at the centers of the pixels.  The PSF is assumed to be the pixel-convolved PSF, so you shouldn't think of pixels as "little boxes"; they are delta-function samples from an underlying smooth surface.

**Comment by dstndstn** [comment]
@davidwhogg - want to say anything?

**Comment by davidwhogg** [comment]
If you are asking about the point that we want the seeing-deconvolved sizes then yes, that's the entire point of *The Tractor*.

**Comment by DriftingPig** [comment]
My test shows that stamp size might have some effect, but it's not significant.
